### ISSUE TITLE
这个是做什么用的，相当于VPN?

### ISSUE THREAD

**Issue by lilyomo** [liudonghua123/system_network_proxy_ynu#3]
rt.
意思是添加这个代理，就能在校外访问知网等资源？

**Comment by liudonghua123** [comment]
这个和vpn不一样，这个是校内的免费代理，只能在校内使用，现在校园网收费了，但是需要保障校内图书馆资源可以免费试用，所以做了这个代理设置程序，之所以使用代理的方案时经过很多论证的，技术细节就不在这里说了。

要是有更好的思路和想法可以实现校内免费使用图书馆资源，也可以分享给我们 😄

**Comment by lilyomo** [comment]
好的，谢谢了。
